export const colors = {
  primary: '#6F8F72',
  primaryDark: '#4F6F52',
  primaryLight: '#DDEADD',
  primarySuperLight: '#F4F8F4',
  secondary: '#D98282',
  secondaryDark: '#B25C5C',
  secondaryLight: '#F3D6D6',
  secondarySoft: '#F5E5E5',
  background: '#F8F9F9',
  surface: '#FFFFFF',
  surfaceSoft: '#EEF5EF',
  routineCircleSoft: '#DFEADF',
  border: '#E1E6E2',
  text: '#102A43',
  textPrimary: '#102A43',
  textSecondary: '#6B7280',
  textMuted: '#9CA3AF',
  textSecondaryLight: '#D1D5DB',
  error: '#BA2A06',
  success: '#A9DFBF',
  pending: '#E1E6E2',
  warning: '#F2C94C',
} as const;

export type ColorName = keyof typeof colors;
